/**
 * Created by kikazheng on 2018/12/6
 */

export const feature = [ //功能确认
  {
    index:1,
    icon:'icon-fadongjiguzhang', //图标
    text:'发动机故障',//文字
    checked:false,//是否选中
    defined:false,//是否自定义
  },
  {
    index:2,
    icon:'icon-jiyouyali',
    text:'机油压力警告',
    checked:false,
    defined:false,
  },
  {
    index:3,
    icon:'icon-dianchiguzhang',
    text:'电池故障',
    checked:false,
    defined:false,
  },
  {
    index:4,
    icon:'icon-zhidongxitong',
    text:'制动系统警告',
    checked:false,
    defined:false,
  },
  {
    index:5,
    icon:'icon-ABSxitong',
    text:'ABS系统故障',
    checked:false,
    defined:false,
  },
  {
    index:6,
    icon:'icon-wudeng',
    text:'雾灯故障',
    checked:false,
    defined:false,
  },
  {
    index:7,
    icon:'icon-ranyou',
    text:'燃油液位低',
    checked:false,
    defined:false,
  },
  {
    index:8,
    icon:'icon-zhuanxiangdeng',
    text:'转向灯故障',
    checked:false,
    defined:false,
  },
  {
    index:9,
    icon:'icon-yuanguangdeng',
    text:'远光灯故障',
    checked:false,
    defined:false,
  },
  {
    index:10,
    icon:'icon-qingxiye',
    text:'清洗液液位低',
    checked:false,
    defined:false,
  },
]
export const goods = [//物品确认
  {
    index:1,
    text:'贵重物品已提醒顾客带离',//文字
    checked:false,//是否选中
    defined:false,//是否自定义
  },
  {
    index:2,
    text:'随车工具',
    checked:false,
    defined:false,
  },
  {
    index:3,
    text:'千斤顶',
    checked:false,
    defined:false,
  },
  {
    index:4,
    text:'备胎',
    checked:false,
    defined:false,
  },
  {
    index:5,
    text:'灭火器',
    checked:false,
    defined:false,
  },
]
export const data = [
  {
    index:-1,//index 序号 小于0为标题
    type:'', //type 区分检查方法 M 目测 D 手动 G专用
    carType:1,//carType 区分车部位 1 车内 2 车外 3底盘 4 轮胎/刹车
    project:'车内检查',
    result:'', //检查结果 0默认 1正常 2异常
    explain:{//说明
      value:[],//选中项
      list:[],//可选项
    },
    scheme:{//解决方案
      value:[],//选中项
      list:[],//可选项
    },
    time:'',//工时
    remark:'',//备注
  },
  {
    index:1,
    type:'D',
    carType:1,
    project:'灯光（小灯、左转向灯......）和喇叭检查',
    result:1,
    explain:{
      value:[],
      list:['XX灯光不亮','喇叭不响'],
    },
    scheme:{
      value:[],
      list:['检查线路','更换喇叭','更换灯泡'],
    },
    time:'',
    remark:'',
  },
  {
    index:2,
    type:'D',
    carType:1,
    project:'雨刮检查（ 有无变形、破裂 ）',
    result:1,
    explain:{
      value:[],
      list:['雨刮磨损严重'],
    },
    scheme:{
      value:[],
      list:['挡风玻璃磨泥','打磨雨刮片','更换雨刮片'],
    },
    time:'',
    remark:'',
  },
  {
    index:3,
    type:'D',
    carType:1,
    project:'四门玻璃升降检查',
    result:1,
    explain:{
      value:[],
      list:['XX玻璃升降不顺','XX玻璃升降失灵'],
    },
    scheme:{
      value:[],
      list:['清洗玻璃胶条','保养升降器','更换升降器','检查线路'],
    },
    time:'',
    remark:'',
  },
  {
    index:4,
    type:'D',
    carType:1,
    project:'空调滤清器检查',
    result:1,
    explain:{
      value:[],
      list:['空调格过脏','细菌滋生，车内有异味'],
    },
    scheme:{
      value:[],
      list:['更换空调格','清洗空调系统'],
    },
    time:'',
    remark:'',
  },
  {
    index:5,
    type:'G',
    carType:1,
    project:'车内PM2.5过滤检测情况',
    result:1,
    explain:{
      value:[],
      list:['PM2.5超标','PM2.5严重超标'],
    },
    scheme:{
      value:[],
      list:['更换空调格','清洗空调系统'],
    },
    time:'',
    remark:'',
  },
  {
    index:6,
    type:'D',
    carType:1,
    project:'安全带检查',
    result:1,
    explain:{
      value:[],
      list:['伸拉不畅','安全带扣无法锁止'],
    },
    scheme:{
      value:[],
      list:['更换安全带','更换安全带扣'],
    },
    time:'',
    remark:'',
  },
  {
    index:7,
    type:'D',
    carType:1,
    project:'驻车制动检查',
    result:1,
    explain:{
      value:[],
      list:['电子手刹声音异常','手刹拉动范围异常'],
    },
    scheme:{
      value:[],
      list:['电子制动泵保养','更换电子制动泵','调整手刹 ','更换手刹拉线'],
    },
    time:'',
    remark:'',
  },
  {
    index:8,
    type:'D',
    carType:1,
    project:'检查仪表信息，有无故障灯亮',
    result:1,
    explain:{
      value:[],
      list:['XX故障灯亮'],
    },
    scheme:{
      value:[],
      list:['电脑检测，读取相应的故障码'],
    },
    time:'',
    remark:'',
  },
  {
    index:-2,
    type:'',
    carType:2,
    project:'车外检查',
    result:0,
    explain:{
      value:[],
      list:[],
    },
    scheme:{
      value:[],
      list:[],
    },
    time:'',
    remark:'',
  },
  {
    index:9,
    type:'M',
    carType:2,
    project:'环车检查车身外观（有无划痕、变形）',
    result:1,
    explain:{
      value:[],
      list:['XX有划痕','XX有变形'],
    },
    scheme:{
      value:[],
      list:['局部抛光，修复漆面','车辆喷漆','钣金修复，喷漆'],
    },
    time:'',
    remark:'',
  },
  {
    index:10,
    type:'D',
    carType:2,
    project:'检查四门门锁',
    result:1,
    explain:{
      value:[],
      list:['XX门中控锁失灵','XX门内/外拉手异常'],
    },
    scheme:{
      value:[],
      list:['更换中控电机','检查线路','维修门拉手，更换门拉手'],
    },
    time:'',
    remark:'',
  },
  {
    index:11,
    type:'D',
    carType:2,
    project:'检查后备箱备胎、工具是否正常',
    result:1,
    explain:{
      value:[],
      list:['备胎气压异常','备用工具丢失'],
    },
    scheme:{
      value:[],
      list:['修补轮胎','修复钢圈','购买工具'],
    },
    time:'',
    remark:'',
  },
  {
    index:-3,
    type:'',
    carType:3,
    project:'底盘检查',
    result:1,
    explain:{
      value:[],
      list:[],
    },
    scheme:{
      value:[],
      list:[],
    },
    time:'',
    remark:'',
  },
  {
    index:12,
    type:'D',
    carType:3,
    project:'紧固底盘螺丝',
    result:1,
    explain:{
      value:[],
      list:['XX螺丝松动','XX螺丝损坏'],
    },
    scheme:{
      value:[],
      list:['紧固螺丝','更换螺丝'],
    },
    time:'',
    remark:'',
  },
  {
    index:13,
    type:'D',
    carType:3,
    project:'检查悬架（转向节/减震/弹簧/稳定杆/下臂/桥梁）',
    result:1,
    explain:{
      value:[],
      list:['XX摆臂球头松动','XX胶套开裂','减震漏油'],
    },
    scheme:{
      value:[],
      list:['更换摆臂球头','更换胶套','更换摆臂','更换减震器'],
    },
    time:'',
    remark:'',
  },
  {
    index:14,
    type:'D',
    carType:3,
    project:'球头销（有无漏油和破裂）',
    result:1,
    explain:{
      value:[],
      list:['球头销松动','球头销防尘套破裂'],
    },
    scheme:{
      value:[],
      list:['更换球头销','球头大修包','更换球头'],
    },
    time:'',
    remark:'',
  },
  {
    index:15,
    type:'D',
    carType:3,
    project:'检查管路和线路（有无漏油和破裂）',
    result:1,
    explain:{
      value:[],
      list:['XX管漏油','XX线破裂'],
    },
    scheme:{
      value:[],
      list:['更换油管','维修线路'],
    },
    time:'',
    remark:'',
  },
  {
    index:16,
    type:'D',
    carType:3,
    project:'车身底部状态（腐蚀/生锈和穿孔）',
    result:1,
    explain:{
      value:[],
      list:['底盘穿孔','底盘生锈'],
    },
    scheme:{
      value:[],
      list:['修补底盘，喷防锈胶','底盘装甲'],
    },
    time:'',
    remark:'',
  },
  {
    index:-4,
    type:'',
    carType:4,
    project:'轮胎/刹车检查',
    result:1,
    explain:{
      value:[],
      list:[],
    },
    scheme:{
      value:[],
      list:[],
    },
    time:'',
    remark:'',
  },
  {
    index:17,
    type:'G',
    carType:4,
    project:'检测刹车片(最低厚度）',
    result:1,
    explain:{
      value:[],
      list:['XX轮刹车片低于3mm','刹车片异响'],
    },
    scheme:{
      value:[],
      list:['更换X（前/后）轮刹车片','刹车保养','更换刹车片'],
    },
    time:0,
    remark:'',
  },
  {
    index:18,
    type:'D',
    carType:4,
    project:'检查轮胎工况、气压（磨损、破裂）',
    result:1,
    explain:{
      value:[],
      list:['XX轮胎漏气','XX轮胎磨损严重','XX轮胎老化'],
    },
    scheme:{
      value:[],
      list:['修补轮胎','更换轮胎'],
    },
    time:'',
    remark:'',
  },
  {
    index:19,
    type:'M',
    carType:4,
    project:'检查轮胎钢圈（有无变形）',
    result:1,
    explain:{
      value:[],
      list:['XX轮胎变形','XX钢圈变形'],
    },
    scheme:{
      value:[],
      list:['更换轮胎','修复钢圈','更换钢圈'],
    },
    time:'',
    remark:'',
  },
  {
    index:20,
    type:'M',
    carType:4,
    project:'检查刹车盘 （有无起槽）',
    result:1,
    explain:{
      value:[],
      list:['XX轮刹车盘磨损严重'],
    },
    scheme:{
      value:[],
      list:['光碟','更换刹车碟'],
    },
    time:'',
    remark:'',
  },
  {
    index:21,
    type:'M',
    carType:4,
    project:'检查刹车油管（老化、肿胀、破裂）',
    result:1,
    explain:{
      value:[],
      list:['XX段刹车油管漏油','XX段刹车油管老化'],
    },
    scheme:{
      value:[],
      list:['更换刹车油管'],
    },
    time:'',
    remark:'',
  },
  {
    index:22,
    type:'D',
    carType:4,
    project:'机油检查（刻度、有无油泥、焦味）',
    result:1,
    explain:{
      value:[],
      list:['超出公里周期','机油量过低','机油杂质过高'],
    },
    scheme:{
      value:[],
      list:['更换机油','加注机油','清洗油泥'],
    },
    time:'',
    remark:'',
  },
  {
    index:23,
    type:'D',
    carType:4,
    project:'波箱油检查（刻度、有无油泥、焦味）',
    result:1,
    explain:{
      value:[],
      list:['超出公里周期','变速箱油杂质过高'],
    },
    scheme:{
      value:[],
      list:['更换变速箱油'],
    },
    time:'',
    remark:'',
  },
  {
    index:24,
    type:'G',
    carType:4,
    project:'电瓶检测（寿命，桩头锈蚀松动等）',
    result:1,
    explain:{
      value:[],
      list:['电瓶膨胀','电瓶桩头氧化','电瓶寿命过低'],
    },
    scheme:{
      value:[],
      list:['更换电瓶','电池养护'],
    },
    time:'',
    remark:'',
  },
  {
    index:25,
    type:'G',
    carType:4,
    project:'冷却液检测（液面刻度、水垢、冰点）',
    result:1,
    explain:{
      value:[],
      list:['超出公里周期','冷却液缺失','冷却液冰点不达标XX度'],
    },
    scheme:{
      value:[],
      list:['更换冷却液'],
    },
    time:'',
    remark:'',
  },
  {
    index:26,
    type:'G',
    carType:4,
    project:'刹车油检测（液面刻度、有无变质）',
    result:1,
    explain:{
      value:[],
      list:['超出公里周期','刹车油缺失','刹车油含水量过高'],
    },
    scheme:{
      value:[],
      list:['更换刹车油','检查刹车片厚度','添加刹车油'],
    },
    time:'',
    remark:'',
  },
  {
    index:27,
    type:'D',
    carType:4,
    project:'动力转向检查（A.液面/含水量/有无杂质 B.线路是否破裂）',
    result:1,
    explain:{
      value:[],
      list:['超出公里周期','方向机油杂质过高','方向机线路破损'],
    },
    scheme:{
      value:[],
      list:['更换方向机油','维修线路'],
    },
    time:'',
    remark:'',
  },
  {
    index:28,
    type:'D',
    carType:4,
    project:'雨刮水检查（液面刻度、添加）',
    result:1,
    explain:{
      value:[],
      list:['雨刮水刻度过低','雨刮水无清洁能力'],
    },
    scheme:{
      value:[],
      list:['添加雨刮水','添加雨刮精'],
    },
    time:'',
    remark:'',
  },
  {
    index:29,
    type:'D',
    carType:4,
    project:'空气格检查（是否过脏、清洁）',
    result:1,
    explain:{
      value:[],
      list:['超出公里周期','空气格过脏'],
    },
    scheme:{
      value:[],
      list:['更换空气格'],
    },
    time:'',
    remark:'',
  },
  {
    index:30,
    type:'D',
    carType:4,
    project:'皮带检查 （有无老化，裂纹）',
    result:1,
    explain:{
      value:[],
      list:['皮带松动','皮带老化'],
    },
    scheme:{
      value:[],
      list:['调节皮带','更换皮带'],
    },
    time:'',
    remark:'',
  },
  {
    index:31,
    type:'D',
    carType:4,
    project:'火花塞检查（燃烧工况，极点烧灼）',
    result:1,
    explain:{
      value:[],
      list:['超出公里周期','陶瓷开裂','中心电极磨损严重','积碳过多'],
    },
    scheme:{
      value:[],
      list:['更换火花塞','A清洗火花塞'],
    },
    time:'',
    remark:'',
  },
  {
    index:32,
    type:'G',
    carType:4,
    project:'燃烧室检测(积炭深积程度)',
    result:1,
    explain:{
      value:[],
      list:['燃烧室积碳过多'],
    },
    scheme:{
      value:[],
      list:['清洗燃烧室积碳'],
    },
    time:'',
    remark:'',
  },
  {
    index:33,
    type:'G',
    carType:4,
    project:'节气门检测(积炭深积程度)',
    result:1,
    explain:{
      value:[],
      list:['节气门积碳过多'],
    },
    scheme:{
      value:[],
      list:['清洗节气门积碳'],
    },
    time:'',
    remark:'',
  },
  {
    index:34,
    type:'M',
    carType:4,
    project:'高压线检查（有无老化、破裂）',
    result:1,
    explain:{
      value:[],
      list:['高压线破裂','高压线老化'],
    },
    scheme:{
      value:[],
      list:['更换高压线'],
    },
    time:'',
    remark:'',
  },
  {
    index:35,
    type:'M',
    carType:4,
    project:'发动机水管检查（有无老化、肿胀）',
    result:1,
    explain:{
      value:[],
      list:['发动机水管肿胀','发动机水管老化'],
    },
    scheme:{
      value:[],
      list:['更换发动机水管'],
    },
    time:'',
    remark:'',
  },
  {
    index:36,
    type:'M',
    carType:4,
    project:'发动机线束检查（线路老化、破裂）',
    result:1,
    explain:{
      value:[],
      list:['发动机线束破裂','发动机线束老化'],
    },
    scheme:{
      value:[],
      list:['修复线束','更换线束'],
    },
    time:'',
    remark:'',
  },
]
